before:
  hooks:
  - go mod download
  
builds:
  - id: lb-check
    binary: lb-check
    dir: cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}}

nfpms:
  - id: default
    package_name: lb-check
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    builds:
      - lb-check

    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS

    homepage: https://github.com/sebastianwebber/lb-check
    maintainer: Sebastian Webber <sebastian@swebber.me>
    description: Another stupid http server that checks if PostgreSQL replica is delayed and running

    license: MIT

    formats:
      - deb
      - rpm

archives:
  - id: lb-check
    builds:
      - lb-check
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc

dockers:
  -
    dockerfile: Dockerfile
    binaries:
    - lb-check
    image_templates:
    - "sebastianwebber/lb-check:{{ .Tag }}"
    - "sebastianwebber/lb-check:{{ .Major }}.{{ .Minor }}"
    - "sebastianwebber/lb-check:latest"
  